### PR TITLE
An attempt to fix clicking sound problem

### PR DESCRIPTION
**Pull request by AlexIII**
Hi! 
First of all let me tell that your project is awesome! 
I'm experimenting on midi playback with YM2413 and while I'm waiting for the real IC's to arrive I decided to work with emulators in the meantime.
There's not much YM2413 emulators on github and I think yours is super amazing! It's self-contained, simple to build and has very convenient API.

Now to the problem that I encountered. I noticed that on voice re-activation (when the key-bit goes on, then off, then on again) there's unwanted loud clicks.
In `sample2413.c` there's only one note playing and it sounds fine. But if you try to rapidly enable/disable a voice (or two), the emulator starts to generate clicking sound (I modified `sample2413.c` in `1f8cfc` so it would reproduce the problem).
Here's an example with two interchanging notes (listen to `before_09a01c_temp.wav` from [temp.zip](https://github.com/digital-sound-antiques/emu2413/files/5862292/temp.zip)).

I noticed that the older versions sounded better and traced the problem to the commit `7c08ba`.
In my commit `09a01c` I returned these lines that were removed in `7c08ba`.
```      
if (buddy) {
    start_envelope(buddy);
}
```
I have no slightest idea on what it actually does and if it's alright to put it here! But it helped a lot, listen to the same example after this change. (`after_09a01c_temp.wav` from [temp.zip](https://github.com/digital-sound-antiques/emu2413/files/5862292/temp.zip))

At fist it seemed like a solution, but if you listen very carefully, you notice that the clicks are still there, they just became less pronounced. They're still very noticeable when playing complex melodies.
I also realized that the clicks are not equally loud between different instruments. They less noticeable with the instrument 1 (violin), almost non-existent with the the instruments 11 (harpsichord) and 13 (synthesizer bass), and more noticeable with the rest. 
[Here's](https://github.com/digital-sound-antiques/emu2413/files/5862294/all-instruments.zip) a short segment of a melody played with all (1-15) instruments (after applying 09a01c).

I can see that you've worked on this project for quite a while and I hope you still have energy left to tackle this. But even if not, thank you for this project, it was very fun to play with! Good luck! 😉

### CODE REVIEW

**Comment by okaxaki** [comment]
Hi, thank you for your pull-request. According to my [research here](https://github.com/digital-sound-antiques/emu2413/wiki/Envelope-Damp-and-KeyOn-Noise), YM2413's loud click noise seems to be a IC's bug or specification. Old emu2413's implementation generates sound clear but it was not correct emulation.

**Comment by AlexIII** [comment]
Ah, sorry I've mistaken this for a bug when It actually was precise emulation. I've never heard real YM2413 and all the recordings I've heard had no out-of-place noises, the composers have probably accounted for YM2413 imperfections in their work.
Disregard my pull request.
Could you answer two follow up questions though?
1. Can this problem be mitigated by some special register-write sequence?
> To remove the noise, we need to enough attenuate the output level of modulator in advance before key-off of the first note.

What did you mean here? The noise can only be masked by means of external hardware or there's a software solution?

2. Is there's a dedicated part in your library that reproduces the clicking or it just happens "along the way"? I would still like to add a control to that feature, so it would be enabled by default, but could be disabled on demand.

**Comment by okaxaki** [comment]
> To remove the noise, we need to enough attenuate the output level of modulator in advance before key-off of the first note.

This means that once the modulator is fully muted, the click noise on the next key-on will be elminated. To mute the modulator, set RR=15, key-off and then wait a few cpu cycle. However, unfortunately, this approach can only be applied for user-defined voice. I think there is no general way to completely eliminate click noise. 

The click noise is sadly, unwanted but I think an important charactaristic of YM2413 (for example, if we eliminate click noise, we will get sotfen bass-drum sound).

> Is there's a dedicated part in your library that reproduces the clicking or it just happens "along the way"? I would still like to add a control to that feature, so it would be enabled by default, but could be disabled on demand.

It just happens "along the way" as a result of accurate emulation. However, if we want to eliminate the click noise, the fix of this pull-request is a right way.

I agree that composers often perfer more noise-free sound than real hardware. Even though some tone effectively uses this noise as an accent, I imagine that the click must be quite annoying in the context of VST/MIDI. I'll carefully consider to implement the option to eliminate click noise.

**Comment by AlexIII** [comment]
Thank you for your answers!

**Pull request closed without merging**
